name: DeepLinking
options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "14.0"

targets:
  DeepLinking:
    type: framework
    platform: iOS

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.blueantcorp.DeepLinking"

    scheme:
      gatherCoverageData: true
      testTargets:
        - name: DeepLinking
          parallelizable: true
          randomExecutionOrder: true
  
    sources:
      - Sources
      - path: Sources/DeepLinking.h
        buildPhase: headers
        headerVisibility: public

  DeepLinkingTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests

    dependencies:
      - target: DeepLinking