extends: default

rules:
  document-start: disable
  line-length:
    max: 120
  truthy: disable
ignore: |
  vendor
  .github/backups/**/*
  .slather.yml
  .swiftlint.yml
  .yamllint.yml
  .rubocop.yml
  .xcodegen.yml