source 'https://rubygems.org'

gem 'danger'
gem 'danger-xcov'
gem 'danger-swiftlint'
gem 'danger-prose'
gem 'danger-slather'
gem 'danger-swiftformat'
gem 'danger-xcode_summary'
gem 'danger-slather'
gem 'slather'
gem 'codecov'
# gem 'xcodegen', '~> 0.4.2'
gem 'sourcery'
gem 'xcpretty'
gem 'fastlane'
