name: Validate
description: Validate project descr

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter json > swiftlint.log

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - uses: actions/upload-artifact@v3
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log