name: Validate
description: Validate project descr

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for Danger
      uses: MeilCli/danger-action@v5
      with:
        danger_id: danger-push
        danger_file: Dangerfile