name: Validate
description: Validate project descr
inputs:
  github-token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
  
    - uses: actions/upload-artifact@v4
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log