name: Build Product
on:
  workflow_call:

jobs:
  slather:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/bootstrap/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: bundle install && bundle exec slather
      env:
        SLATER_COVERAGE_SERVICE: 'github-actions'
        SLATER_GITHUB_ACTIONS: 'true'
        SLATER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLATER_GITHUB_WORKFLOW: ${{ github.workflow }}
        SLATER_GITHUB_RUN_ID: ${{ github.run_id }}
        SLATER_GITHUB_RUN_NUMBER: ${{ github.run_number }}
        SLATER_GITHUB_REF: ${{ github.ref }}
        SLATER_GITHUB_SHA: ${{ github.sha }}
        SLATER_GITHUB_REPOSITORY: ${{ github.repository }}
        SLATER_GITHUB_ACTOR: ${{ github.actor }}
        SLATER_GITHUB_EVENT_NAME: ${{ github.event_name }}
        SLATER_GITHUB_WORKSPACE: ${{ github.workspace }}
        SLATER_INPUT_COVERAGE_SERVICE: 'github-actions'
        SLATER_INPUT_GITHUB_ACTIONS: 'true'
        SLATER_INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLATER_INPUT_GITHUB_WORKFLOW: ${{ github.workflow }}
        iconv: 'true'

  danger:
    needs: slather
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/bootstrap/
    - run: bundle install 

    - name: Run Danger
      run: bundle exec danger
      env:
        DANGER_ID: 'danger-ci'
        GITHUB_TOKEN: ${{ github.token }}
        DANGER_GITHUB_API_TOKEN: ${{ github.token }}
        DANGER_GITHUB_BEARER_TOKEN: ${{ github.token }}

  codecov:
    needs: slather
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: mattpolzin/swift-codecov-action@0.7.5
      with:
        MINIMUM_COVERAGE: 90
        INCLUDE_TESTS: "true"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  sonarcloud:
    needs: slather
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: SonarCloud Scan
      run: echo ${{ secrets.SONAR_TOKEN }}
    - uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}