name: Static Analysis
on: 
  workflow_call:
    secrets:
      DANGER_GITHUB_API_TOKEN:
        description: 'GitHub API token'
        required: true
      CODECOV_TOKEN:
        description: 'Codecov token'
        required: true
      SONAR_TOKEN:
        description: 'SonarCloud token'
        required: true

jobs:

  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: openbynature/swifty-code-coverage@v1.0.2
        with:
          build-path: .build
          target: DeepLinkingPackageTests.xctest
          is-spm: true

  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: danger/swift@3.16.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
  
  codecov:
    needs: code-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: code-coverage-artifact
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: fail
  
  sonarcloud:
    needs: code-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: code-coverage-artifact
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}