name: Static Analysis
on: 
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token'
        required: true
      DANGER_GITHUB_API_TOKEN:
        description: 'GitHub API token'
        required: true
      SONAR_TOKEN:
        description: 'SonarCloud token'
        required: true

jobs:

  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run Danger
      run: bundle exec danger

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ github.token }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}