name: Static Analysis
on: 
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'SonarCloud token'
        required: true

jobs:

  danger:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/bootstrap/

    - name: Run Danger
      run: bundle exec danger
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DANGER_GITHUB_API_TOKEN: ${{ github.token }}
        DANGER_GITHUB_BEARER_TOKEN: ${{ github.token }}

  sonarcloud:
    needs: danger
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ github.token }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}