name: Static Analysis
on: 
  workflow_call:
    secrets:
      DANGER_GITHUB_API_TOKEN:
        description: 'GitHub API token'
        required: true
      SONAR_TOKEN:
        description: 'SonarCloud token'
        required: true

jobs:

  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: danger/swift@v3.16.0
      with:
        github_token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: code-coverage-artifact
    - uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ github.token }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}