name: Build/Test
on:
  workflow_call:

jobs:
  build:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: |
        swift build -v \
          --enable-test-discovery \
          --enable-code-coverage

  test:
    # needs: build
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Package
      run: |
        swift test \
          --enable-test-discovery \
          --enable-code-coverage

    - name: Prepare Code Coverage
      run: llvm-cov export -format="lcov" .build/x86_64-unknown-linux-gnu/debug/${{ env.PACKAGE_NAME }}PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash)
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}