name: Build/Test
on:
  workflow_call:

jobs:
  build:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: |
        swift build -v \
          --enable-test-discovery \
          --enable-code-coverage

  test:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Package
        run: |
          swift test \
            --enable-test-discovery \
            --enable-code-coverage

      - uses: openbynature/swifty-code-coverage@v1.0.2
        with:
          build-path: .build
          target: .build/debug/DeepLinkingPackageTests.xctest
          is-spm: true
      
      - name: Upload to Codecov
        run: |
          bash <(curl https://codecov.io/bash) -f "coverage/*.info"
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}