name: Build/Test
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: swift build -v

  test:
    if: ${{ false }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Package
      run: |
        swift test \
          --enable-test-discovery \
          --enable-code-coverage

  test-osx:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Package
      run: |
        xcodebuild test \
          -scheme Rester \
          -destination platform="iOS" \
          -enableCodeCoverage YES \
          -derivedDataPath .build/derivedData