name: Build Product
on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Archiving..."

  provision:
    needs: archive
    runs-on: ubuntu-latest
    steps:
    - name: Provision
      run: echo "Provisioning..."

  export:
    needs: provision
    runs-on: ubuntu-latest
    steps:
    - name: Export
      run: echo "Exporting..."