name: Build Product
on:
  workflow_call:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Archiving..."

  provision:
    runs-on: ubuntu-latest
    steps:
    - name: Provision
      run: echo "Provisioning..."

  export:
    runs-on: ubuntu-latest
    steps:
    - name: Export
      run: echo "Exporting..."