name: CI
on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
  FASTLANE_SKIP_UPDATE_CHECK: true
  FASTLANE_XCODE_LIST_TIMEOUT: 60
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
  HOMEBREW_NO_INSTALL_CLEANUP: TRUE
  BUNDLE_PATH: vendor/bundle

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: YamlLint
        run: yamllint --strict --format github .
      - name: RuboCop
        run: bundle exec rubocop --format github
      - name: SwiftLint
        run: |
          docker run --rm -v `pwd`:`pwd` -w `pwd` \
            ghcr.io/realm/swiftlint:0.49.1 \
            swiftlint lint --strict --config .swiftlint.yml --reporter github-actions-logging
      - name: SwiftFormat
        run: |
          docker run --rm -v `pwd`:`pwd` -w `pwd` \
            ghcr.io/nicklockwood/swiftformat:0.50.3 \
            --lint --config .swiftformat .