# env:
#   DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
#   FASTLANE_SKIP_UPDATE_CHECK: true
#   FASTLANE_XCODE_LIST_TIMEOUT: 60
#   FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
#   HOMEBREW_NO_INSTALL_CLEANUP: TRUE
#   BUNDLE_PATH: vendor/bundle

name: CI
on: 
  pull_request:
    types: [opened, synchronize]
    branches: [main, develop]

jobs:

  # Lint, build and test
  lint-build-test:
    if: ${{ false }}
    uses: ./.github/workflows/lint-build-test.yml

  build-product:
    needs: lint-build-test
    uses: ./.github/workflows/build-product.yml

  # Analyze code
  analyze:
    # needs: lint-build-test
    uses: ./.github/workflows/analyze.yml
    secrets: inherit
  
  # Generate documentation
  documentation:
    needs: [analyze]
    runs-on: ubuntu-latest
    steps:
    - name: Documentation
      run: echo "Generating Documentation ..."
  
  #
  publish:
    needs: [documentation, build-product]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "Publishing..."