name: CI
on: [push, pull_request]

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/bootstrap    
  
  # validate:
  #   needs: [bootstrap]
  #   uses: ./.github/workflows/validate.yml
    
  build:
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Package
        run: swift build -v

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Package
        run: |
          swift test \
            --enable-test-discovery \
            --enable-code-coverage
  
  codecov:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mattpolzin/swift-codecov-action@0.7.5
        with:
          MINIMUM_COVERAGE: 90
          INCLUDE_TESTS: "true"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  sonarcloud:
    needs: [test]
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}





  analyze:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  slather:
    if: ${{ false }}
    needs: [analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: bundle exec slather

  format:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mtgto/swift-format-action@main
        with:
          configuration_file: .swift-format
          all_files: false
          auto_correct: true
          max_warnings: -1

  docs:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  release:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  publish:
    if: ${{ false }}
    name: Publish on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


