name: CI
on: [push, pull_request]

jobs:
  bootstrap:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
    
  build:
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
#      - uses: ./.github/actions/bootstrap
      - name: Build Package
        run: swift build -v
        
  test:
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
      - name: Test Package
        run: |
          swift test \
            --enable-test-discovery \
            --enable-code-coverage

  slather:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: bundle exec slather
      
  codecov:
    needs: [slather]
    runs-on: ubuntu-latest
    steps:
      - uses: mattpolzin/swift-codecov-action@0.7.5
        with:
          MINIMUM_COVERAGE: 90
          INCLUDE_TESTS: 'true'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

#name: Lint
#on:
#  pull_request:
#    paths:
#      - '.github/workflows/swiftlint.yml'
#      - '.swiftlint.yml'
#      - '**/*.swift'
#
#jobs:
#  SwiftLint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      
#      - name: GitHub Action for SwiftLint
#        uses: norio-nomura/action-swiftlint@3.2.1
#      
#      - name: GitHub Action for SwiftLint with --strict
#        uses: norio-nomura/action-swiftlint@3.2.1
#        with:
#          args: --strict
#      
#      - name: GitHub Action for SwiftLint (Only files changed in the PR)
#        uses: norio-nomura/action-swiftlint@3.2.1
#        env:
#          DIFF_BASE: ${{ github.base_ref }}
#      
#      - name: GitHub Action for SwiftLint (Different working directory)
#        uses: norio-nomura/action-swiftlint@3.2.1
#        env:
#          WORKING_DIRECTORY: Source


#  Danger:
#    - name: Danger
#      run: echo 'Danger'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      # Ruby
#      - name: Set up Ruby latest
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 'head'
#      - name: Install dependencies
#        run: |
#            bundle install \
#                --without=documentation \
#                --jobs 4 \
#                --retry 3

      # Slather
#      - run: bundle exec slather
#        env:
#          GIT_BRANCH: ${{ steps.get_branch.outputs.branch }}
#          CI_PULL_REQUEST: ${{ github.event.number }}
#          COVERAGE_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Danger
      #   run: bundle exec danger
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - uses: actions/upload-artifact@v2
#        if: ${{ always() }}
#        with:
#          name: ResultBundle
#          path: ./coverage/*.xcresult
#          if-no-files-found: warn
#          retention-days: 5
#
#      - name: Clean up
#        if: ${{ always() }}
#        run: make cleanup
