# env:
#   DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
#   FASTLANE_SKIP_UPDATE_CHECK: true
#   FASTLANE_XCODE_LIST_TIMEOUT: 60
#   FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
#   HOMEBREW_NO_INSTALL_CLEANUP: TRUE
#   BUNDLE_PATH: vendor/bundle

name: CI
on: [push]
  
jobs:
  codecov:
    runs-on: macos-11

    steps:
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Build Package
        run: swift build -v

      - name: Run tests
        run: swift test --enable-code-coverage -v
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: "13.1"

      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/{YOUR_PACKAGE_NAME}PackageTests.xctest/Contents/MacOS/{YOUR_PACKAGE_NAME}PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: fail
          files: ./coverage_report.lcov
          verbose: true

  # Validate code 
  validate:
    if: ${{ false }}
    uses: ./.github/workflows/validate.yml

  # Build and test
  build-test:
    needs: validate
    uses: ./.github/workflows/build-test.yml

  # Build product
  build-product:
    needs: build-test
    uses: ./.github/workflows/build-product.yml

  # Analyze code
  analyze:
    needs: build-test
    uses: ./.github/workflows/analyze.yml
    secrets: inherit
  
  # Generate documentation
  documentation:
    needs: analyze
    uses: ./.github/workflows/documentation.yml
  
  #
  publish:
    needs: [documentation, build-product]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "Publishing..."