name: CI
on: [push, pull_request]

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ github.token }}
  
    - uses: actions/upload-artifact@v3
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log

  build:
    needs: [swiftlint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: swift build -v

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Package
      run: |
        swift test \
          --enable-test-discovery \
          --enable-code-coverage

  slather:
    if: ${{ false }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up ruby env
      uses: ruby/setup-ruby@v1.138.0
      with:
        ruby-version: 3.0
        bundler-cache: true
    - run: bundle exec slather
          
  danger:
    needs: [slather]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run Danger
      run: bundle exec danger
      env:
        DANGER_ID: 'danger-ci'
        GITHUB_TOKEN: ${{ github.token }}
        DANGER_GITHUB_API_TOKEN: ${{ github.token }}
        DANGER_GITHUB_BEARER_TOKEN: ${{ github.token }}
  codecov:
    needs: [slather]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mattpolzin/swift-codecov-action@0.7.5
      with:
        MINIMUM_COVERAGE: 90
        INCLUDE_TESTS: "true"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  sonarcloud:
    needs: [slather]
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  archive:
    if: ${{ false }}
    needs: [build]
    runs-on: ubuntu-latest

  provision:
    needs: [archive]
    runs-on: ubuntu-latest
  
  publish:
    if: ${{ false }}
    name: Publish on GitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
  format:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mtgto/swift-format-action@main
      with:
        configuration_file: .swift-format
        all_files: false
        auto_correct: true
        max_warnings: -1

  docs:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3