name: CI
on: [push, pull_request]

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ github.token }}
  
    - uses: actions/upload-artifact@v3
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log

  build-test:
    needs: swiftlint
    
    uses: ./.github/workflows/build-test.yml

  analyze:
    needs: build-test
    uses: ./.github/workflows/analyze.yml

  build-product:
    needs: analyze
    uses: ./.github/workflows/build-product.yml
  
  documentation:
    needs: analyze
    uses: ./.github/workflows/documentation.yml
  
  publish:
    needs: [documentation, build-product]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "Publishing..."