name: CI
on: [push, pull_request]

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ github.token }}
  
    - uses: actions/upload-artifact@v3
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log

  build-test:
    needs: [swiftlint]
    uses: ./.github/workflows/build-test.yml

  slather:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1.138.0
      with:
        bundler-cache: true
    - run: bundle exec slather
          
  danger:
    needs: [build-test]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run Danger
      run: bundle exec danger
      env:
        DANGER_ID: 'danger-ci'
        GITHUB_TOKEN: ${{ github.token }}
        DANGER_GITHUB_API_TOKEN: ${{ github.token }}
        DANGER_GITHUB_BEARER_TOKEN: ${{ github.token }}

  codecov:
    needs: [slather]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mattpolzin/swift-codecov-action@0.7.5
      with:
        MINIMUM_COVERAGE: 90
        INCLUDE_TESTS: "true"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  sonarcloud:
    needs: [codecov]
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-product:
    needs: [sonarcloud]
    uses: ./.github/workflows/build-product.yml
  
  documentation:
    needs: [swiftlint]
    uses: ./.github/workflows/documentation.yml
  
  publish:
    needs: [documentation]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "Publishing..."