# env:
#   DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
#   FASTLANE_SKIP_UPDATE_CHECK: true
#   FASTLANE_XCODE_LIST_TIMEOUT: 60
#   FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
#   HOMEBREW_NO_INSTALL_CLEANUP: TRUE
#   BUNDLE_PATH: vendor/bundle

name: CI
on: [push]
  
jobs:
  codecov:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: |
          swift test \
            --enable-test-discovery \
            --enable-code-coverage

      - uses: sersoft-gmbh/swift-coverage-action@v3
        id: coverage-files

      - uses: codecov/codecov-action@v3
        with:
          files: ${{join(fromJSON(steps.coverage-files.outputs.files), ',')}}

  # Validate code 
  validate:
    if: ${{ false }}
    uses: ./.github/workflows/validate.yml

  # Build and test
  build-test:
    needs: validate
    uses: ./.github/workflows/build-test.yml

  # Build product
  build-product:
    needs: build-test
    uses: ./.github/workflows/build-product.yml

  # Analyze code
  analyze:
    needs: build-test
    uses: ./.github/workflows/analyze.yml
    secrets: inherit
  
  # Generate documentation
  documentation:
    needs: analyze
    uses: ./.github/workflows/documentation.yml
  
  #
  publish:
    needs: [documentation, build-product]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "Publishing..."