name: CI
on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
  FASTLANE_SKIP_UPDATE_CHECK: true
  FASTLANE_XCODE_LIST_TIMEOUT: 60
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
  HOMEBREW_NO_INSTALL_CLEANUP: TRUE
  BUNDLE_PATH: vendor/bundle

  WORKFLOW_PATH: .github/workflows
  
jobs:
  swiftlint:
    if: ${{ false }}
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ github.token }}
  
    - uses: actions/upload-artifact@v3
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log

  build-test:
    # needs: swiftlint
    uses: ${WORKFLOW_PATH}/build-test.yml

  build-product:
    needs: build-test
    uses: ./.github/workflows/build-product.yml

  analyze:
    needs: build-test
    uses: ./.github/workflows/analyze.yml
  
  documentation:
    needs: analyze
    uses: ./.github/workflows/documentation.yml
  
  publish:
    needs: [documentation, build-product]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "Publishing..."