env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
  FASTLANE_SKIP_UPDATE_CHECK: true
  FASTLANE_XCODE_LIST_TIMEOUT: 60
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
  HOMEBREW_NO_INSTALL_CLEANUP: TRUE
  BUNDLE_PATH: vendor/bundle

  # Workaround for long path issue
  WORKFLOW_PATH: ./.github/workflows

name: CI
on: [push, pull_request]
  
jobs:

  code-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - run: swift test --enable-code-coverage
      - uses: michaelhenry/swifty-code-coverage@v1.0.0
        with:
          build-path: .build
          target: GithubChecksPackageTests.xctest
          is-spm: true
      - name: Upload to Codecov
        run: |
          bash <(curl https://codecov.io/bash) -f "coverage/*.info"
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Validate code 
  validate:
    if: ${{ false }}
    uses: ./.github/workflows/validate.yml

  # Build and test
  build-test:
    needs: validate
    uses: ./.github/workflows/build-test.yml

  # Build product
  build-product:
    needs: build-test
    uses: ./.github/workflows/build-product.yml

  # Analyze code
  analyze:
    needs: build-test
    uses: ./.github/workflows/analyze.yml
    secrets: inherit
  
  # Generate documentation
  documentation:
    needs: analyze
    uses: ./.github/workflows/documentation.yml
  
  #
  publish:
    needs: [documentation, build-product]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "Publishing..."