name: Validate
on:
    workflow_call:

jobs:
  SwiftLint:
    runs-on: composite
    steps:
      - uses: actions/checkout@v3
      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict --config ./.swiftlint.yml
  
  Danger:
    runs-on: composite
    steps:
    - uses: MeilCli/danger-action@v5
      with:
        danger_file: '.github/Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}