name: Lint/Build/Test
on: 
  workflow_call:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Run swiftlint
      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --reporter json > swiftlint.log
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Upload the swiftlint log as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: swiftlint
          path: |
            ./.swiftlint.yml
            ./swiftlint.log
  
      - name: Build Package
        run: |
          swift build -v

      - name: Test Package
        run: |
          swift test \
            --enable-test-discovery \
            --enable-code-coverage

      - uses: openbynature/swifty-code-coverage@v1.0.2
        with:
          build-path: .build
          target: DeepLinkingPackageTests.xctest
          is-spm: true
      
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: fail
