name: Lint
on:
  workflow_call:
  # pull_request:
  #   paths:
  #     - '.github/workflows/lint.yml'
  #     - '.swiftlint.yml'
  #     - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: composite
    steps:
      - uses: actions/checkout@v3
      - uses: norio-nomura/action-swiftlint@3.2.1
