name: Lint
on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Lint
      - name: Lint code using SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
