name: test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
jobs:
  codecov:
    container:
      image: swift:5.8
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v3
      with:
        bundler-cache: true

    - name: Install bundler
      run: |
        gem install bundler
        bundler install

    - name: Run tests
      run: make test
    
    - name: Collect code coverage
      uses: codecov/codecov-action@v3

name: test

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run tests
        run: make test

      # - name: Danger
      #   run: bundle exec danger
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ResultBundle
          path: ./coverage/*.xcresult
          if-no-files-found: warn
          retention-days: 5

      - name: Clean up
        if: ${{ always() }}
        run: make cleanup
