name: Test
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Ruby
      - name: Set up Ruby latest
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'head'
      - name: Install dependencies
        run: bundle install
        
      # Swift
      - name: Run tests and collect coverage
        run: |
            swift test \
                --enable-code-coverage \
                | xcpretty
            
            bundle exec slather
#            llvm-cov export -format="lcov" \
#                .build/debug/DeepLinking/PackageTests.xctest \
#                -instr-profile .build/debug/codecov/default.profdata \
#                > info.lcov
      
      # Slather
      - name: Rund Slather
#        run: slather
      
      # Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      # - name: Danger
      #   run: bundle exec danger
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - uses: actions/upload-artifact@v2
#        if: ${{ always() }}
#        with:
#          name: ResultBundle
#          path: ./coverage/*.xcresult
#          if-no-files-found: warn
#          retention-days: 5
#
#      - name: Clean up
#        if: ${{ always() }}
#        run: make cleanup
