name: CI
on: [push, pull_request]

jobs:
  bootstrap:
    name: Bootstrap
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
    
  build:
    name: Build Package
    needs: [bootstrap]
    steps:
      - uses: ./.github/actions/bootstrap
      - name: Build Package
        run: swift build -v
        
  test:
    needs: [bootstrap]
    steps:
      - name: Test Package
        run: |
          swift test \
            --enable-test-discovery \
            --enable-code-coverage

       # Slather
       #- run: bundle exec slather
      
  codecov:
    needs: [bootstrap, test]
    steps:
      - uses: mattpolzin/swift-codecov-action@0.7.5
        with:
          MINIMUM_COVERAGE: 90
          INCLUDE_TESTS: 'true'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
