name: Validate
on:
    workflow_call:

jobs:
  swiftlint:
    name: Run SwiftLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --fix --config ./.swiftlint.yml
  
  danger:
    name: Run Danger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: MeilCli/danger-action@v5
      with:
        danger_file: '.github/Dangerfile'
        danger_id: 'danger-pr'
      # env:
      #   DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}