name: Validate
on:
    workflow_call:

jobs:
  swiftlint:
    name: Run SwiftLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - uses: actions/upload-artifact@v2
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log
  
  danger:
    name: Run Danger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: MeilCli/danger-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dangerfile_path: ./Dangerfile
        danger_id: ${{ github.event.pull_request.head.sha }}
        danger_version: 10.5.0
        danger_plugins: