name: validate
on: workflow_call

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Run swiftlint
      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --reporter json > swiftlint.log
        env:
          GITHUB_TOKEN: ${{ github.token }}
    
      # Upload the swiftlint log as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: swiftlint
          path: |
            ./.swiftlint.yml
            ./swiftlint.log
