name: Validate
on:
    workflow_call:
      inputs:
        runs-on:
          description: 'The type of runner that the job will run on'
          default: ubuntu-latest
          required: true
          type: string

jobs:
  SwiftPackage:
    runs-on: composite
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Validate Package
      run: swift package validate 

  SwiftLint:
    runs-on: composite
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict --config ./.swiftlint.yml
  
  Danger:
    runs-on: composite
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: MeilCli/danger-action@v5
      with:
        danger_file: '.github/Dangerfile'
        danger_id: 'danger-pr'
      # env:
      #   DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}