name: Validate
on:
  workflow_call:

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ github.token }}
  
    - uses: actions/upload-artifact@v3
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log
  
  danger:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true


    - name: Run Danger
      run: bundle exec danger
      env:
        DANGER_ID: 'danger-CI'
        
        # This is the token that is used to authenticate with GitHub.
        GITHUB_TOKEN: ${{ github.token }}

        # This is the token that is used to authenticate with Danger.
        DANGER_GITHUB_BEARER_TOKEN: ${{ github.danger_bearer_token }}
        DANGER_GITHUB_API_BASE_URL: ${{ github.github_api_base_url }}

        SWIFTLINT_REPORT_FILE: ${{ github.workspace }}/swiftlint.log

        SWIFTLINT_REPORTER: json
        SWIFTLINT_REPORTER_OUTPUT: swiftlint.log
        SWIFTLINT_REPORTER_OUTPUT_DIR: ${{ github.workspace }}
        SWIFTLINT_REPORTER_OUTPUT_FILE: swiftlint.log
        SWIFTLINT_REPORTER_OUTPUT_PATH: ${{ github.workspace }}/swiftlint.log
        SWIFTLINT_REPORTER_OUTPUT_PATHS: ${{ github.workspace }}/swiftlint.log

        # SwiftLint
        SWIFTLINT_USE_BUNDLER: true
        SWIFTLINT_USE_BUNDLER_EXEC: true
        SWIFTLINT_FORCE_BUNDLE_EXEC: true
        SWIFTLINT_IGNORE_FILE: .swiftlint.yml
        SWIFTLINT_FAIL_ON_ERROR: true
        SWIFTLINT_INLINE_MODE: true
        SWIFTLINT_ENABLED: true
        SWIFTLINT_PATH: ./.swiftlint.yml
        SWIFTLINT_EXECUTABLE: bundle exec swiftlint