name: Validate product
on: 
  workflow_call:
    secrets:
      DANGER_GITHUB_API_TOKEN:
        required: true

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/nicklockwood/SwiftFormat
          version: '*'
      
      - name: Lint
        run: |
          swiftformat --lint . \
            --lenient \
            --swiftversion 5.8 \
            --reporter "emoji" > swiftlint.log || true

      - name: Format
        run: | 
          swiftformat . \
            --swiftversion 5.8

      - uses: actions/upload-artifact@v3
        with:
          name: swiftlint
          path: |
            ./.swiftlint.yml
            ./swiftlint.log

  build-test:
    needs: lint-format
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - uses: actions/checkout@v3
      - uses: mikehardy/buildcache-action@v2

      - name: Build
        run: swift build 
  
      - name: Test
        run: |
          swift test \
            --enable-test-discovery \
            --enable-code-coverage \
            --parallel
  
  danger:
    if: ${{ false }}
    needs: build-test
    runs-on: ubuntu-latest
    container: danger/swift:slim
    steps:
      - uses: actions/checkout@v3
      - uses: danger/swift@3.16.0
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          