name: Run code validation
on:
    workflow_call:

jobs:
  swiftlint:
    if: ${{ false }}
    name: Run SwiftLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict --reporter json > swiftlint.log
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - uses: actions/upload-artifact@v2
      with:
        name: swiftlint
        path: |
          ./.swiftlint.yml
          ./swiftlint.log
  
  danger:
    name: "Run Danger"
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run Danger
      run: bundle exec danger
      env:
        # This is the
        danger_id: 'Build'
        
        # This is the token that is used to authenticate with GitHub.
        github_token: ${{ secrets.GITHUB_TOKEN }}

        # This is the token that is used to authenticate with Danger.
        danger_token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        danger_github_api_token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        danger_github_bearer_token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        
        # SwiftLint settings
        swiftlint_enabled: true
        swiftlint_inline_mode: true
        swiftlint_fail_on_error: true
        swiftlint_ignore_file: .swiftlint.yml
        swiftlint_reporter: json
        swiftlint_report_file: swiftlint.log
        swiftlint_use_bundler: true
        swiftlint_use_bundler_exec: true
        swiftlint_force_bundle_exec: true
  